// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 9 "A Ktor server is one expression".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide9

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun main() {
  embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
    routing {
      get("/") {
        call.respondText(
          text = "Hello world!",
          status = HttpStatusCode.OK,
        )
      }
    }
  }.start(wait = true)
}
