// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 10 "The handler is typed, the route is not".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide10

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    get("/") {
      call.respondText("Hello world!")
    }
  }
}
