// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 18 "Plug-ins are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide18

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.compression.Compression
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation

fun Application.module() {
  install(ContentNegotiation) {
    json()
  }
  install(Compression)
}
