// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 19 "Plug-ins are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide19

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.compression.Compression
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  install(ContentNegotiation) {
    json()
  }
  install(Compression)

  routing {
    get("/") {
      call.respondText("Hello world!")
    }
  }
}
