// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 20 "`ContentNegotiation` wraps the handler".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide20

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  install(ContentNegotiation) { json() }
  routing {
    post("/greet") {
      val greeting = call.receive<Greeting>()
      call.respond(greeting)
    }
  }
}
