// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 22 "Plug-ins are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide22

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.compression.Compression
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  install(ContentNegotiation) { json() }
  install(Compression) {
    mode = CompressionConfig.Mode.All
    maxEncodingChainLength = 2
    maxDecodedContentLength = -1

    gzip()
    deflate()
    identity()

    minimumSize(200)

    excludeContentType(Audio.Any, Video.Any, Image.Any, Text.EventStream)
  }
