// Generated by slidev-theme-kotlin from lessons/lesson-1.md, slide 22 "Plug-ins are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson1.slide22

import presentation.support.*
import io.ktor.http.ContentType.Audio
import io.ktor.http.ContentType.Image
import io.ktor.http.ContentType.Text
import io.ktor.http.ContentType.Video
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.compression.Compression
import io.ktor.server.plugins.compression.CompressionConfig
import io.ktor.server.plugins.compression.deflate
import io.ktor.server.plugins.compression.excludeContentType
import io.ktor.server.plugins.compression.gzip
import io.ktor.server.plugins.compression.identity
import io.ktor.server.plugins.compression.minimumSize
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation

fun Application.module() {
  install(ContentNegotiation) { json() }
  install(Compression) {
    mode = CompressionConfig.Mode.All
    maxEncodingChainLength = 2
    maxDecodedContentLength = -1

    gzip()
    deflate()
    identity()

    minimumSize(200)

    excludeContentType(Audio.Any, Video.Any, Image.Any, Text.EventStream)
  }
}
