// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 49 "A route is a class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide49

import presentation.support.*
import io.ktor.resources.Resource
import kotlinx.serialization.Serializable

@Serializable
@Resource("/bye/{name}")
class Bye(val name: String)
