// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 51 "A route is a class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide51

import presentation.support.*
import io.ktor.resources.Resource
import kotlinx.serialization.Serializable

@Serializable
@Resource("/bye/{name}")
class Bye(val name: String)

@Serializable
@Resource("/hello/{name}/{hour}")
class Hello(
  val name: String,
  val hour: Int,
  val lang: String? = "en",
)
