// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 52 "A route is a class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide52

import presentation.support.*
import io.ktor.resources.Resource
import kotlinx.serialization.Serializable

@Serializable
@Resource("/greet/{name}")
class Greeting(val name: String, val lang: String? = "en") {
  @Serializable
  @Resource("bye")
  class Bye(val parent: Greeting)

  @Serializable
  @Resource("hello/{hour}")
  class Hello(val parent: Greeting, val hour: Int)
}
