// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 53 "Headers are a map on both sides".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide53

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.header
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    get("/hello") {
      val requestId: String? = call.request.headers["X-Request-Id"]
      call.response.header("X-Served-By", "ktor")
      call.respondText("Hello, request $requestId")
    }
  }
}
