// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 53 "A query parameter is a property too".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide53

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  routing {
    get("/bye/{name}") {
      val name: String by call.pathParameters
      call.respondText("Bye, $name")
    }
    get("/hello/{name}/{hour}") {
      val name: String by call.pathParameters
      val hour: Int by call.pathParameters
      val lang: String? by call.queryParameters
      val hello = if (lang == "nl") "Hallo" else "Hello"
      call.respondText("$hello, $name, it's $hour o'clock")
    }
  }
}
