// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 54 "The plug-in does the matching".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide54

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.resources.Resources
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.module() {
  install(Resources)
  routing {
    get<Greeting.Bye> { req ->
      call.respondText("Bye, ${req.parent.name}")
    }
    get<Greeting.Hello> { req ->
      call.respondText("Hello, ${req.parent.name}, it's ${req.hour} o'clock")
    }
  }
}
