// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 55 "Routes group by prefix".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide55

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.route
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  routing {
    route("/greet/{name}") {
      get("bye") {
        val name: String by call.pathParameters
        call.respondText("Bye, $name")
      }
      get("hello/{hour}") {
        val name: String by call.pathParameters
        val hour: Int by call.pathParameters
        call.respondText("Hello, $name, it's $hour o'clock")
      }
    }
  }
}
