// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 55 "Routes are extensions of `Route`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide55

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.resources.Resources
import io.ktor.server.resources.delete
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.Route
import io.ktor.server.routing.routing

fun Route.helloRoutes() {
  get<Greeting.Hello> { req ->
    call.respondText("Hello, ${req.parent.name}, it's ${req.hour} o'clock")
  }
}

fun Application.module() {
  install(Resources)
  routing {
    byeRoutes()
    helloRoutes()
  }
}

fun Route.byeRoutes() {
  get<Greeting.Bye> { req ->
    call.respondText("Bye, ${req.parent.name}")
  }
  delete<Greeting.Bye> { req ->
    call.respondText("I don't like you either, ${req.parent.name}")
  }
}
