// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 56 "The request line is the route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide56

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    get("/hello/{name}") {
      val name = call.parameters["name"]
      call.respondText("Hello, $name")
    }
  }
}
