// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 56 "Handlers are extensions of `RoutingContext`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide56

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.resources.Resources
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext
import io.ktor.server.routing.routing

fun Application.module() {
  install(Resources)
  routing {
    get<Greeting.Bye> { bye(it) }
    get<Greeting.Hello> { hello(it) }
  }
}

suspend fun RoutingContext.bye(req: Greeting.Bye) {
  call.respondText("Bye, ${req.parent.name}")
}

suspend fun RoutingContext.hello(req: Greeting.Hello) {
  call.respondText("Hello, ${req.parent.name}, it's ${req.hour} o'clock")
}
