// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 57 "Every parameter arrives as a `String?`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide57

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    get("/bye/{name}") {
      call.respondText("Bye, ${call.parameters["name"]}")
    }
    get("/hello/{name}/{hour}") {
      val name = call.parameters["name"]
      val hour = call.parameters["hour"]?.toInt()
      call.respondText("Hello, $name, it's $hour o'clock")
    }
  }
}
