// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 57 "The logic does not need Ktor at all".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide57

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.resources.Resources
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.module() {
  install(Resources)
  routing {
    get<Greeting.Bye> { call.respondText(bye(it)) }
    get<Greeting.Hello> { call.respondText(hello(it)) }
  }
}

fun bye(req: Greeting.Bye): String = "Bye, ${req.parent.name}"

fun hello(req: Greeting.Hello): String =
  "Hello, ${req.parent.name}, it's ${req.hour} o'clock"
