// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 58 "Routes are extensions of `Route`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide58

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.Route
import io.ktor.server.routing.delete
import io.ktor.server.routing.get
import io.ktor.server.routing.route
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Route.helloRoutes() {
  get("hello/{hour}") {
    val name: String by call.pathParameters
    val hour: Int by call.pathParameters
    call.respondText("Hello, $name, it's $hour o'clock")
  }
}

fun Application.module() {
  routing {
    greetRoutes()
  }
}

fun Route.greetRoutes() = route("/greet/{name}") {
  get("bye") {
    val name: String by call.pathParameters
    call.respondText("Bye, $name")
  }
  delete("bye") {
    val name: String by call.pathParameters
    call.respondText("I don't like you either, $name")
  }
  helloRoutes()
}
