// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 59 "HTML is a Kotlin DSL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide59

import presentation.support.*
import io.ktor.server.html.respondHtml
import io.ktor.server.routing.RoutingContext
import kotlinx.html.*

suspend fun RoutingContext.hello(req: Greeting.Hello) {
  call.respondHtml {
    head {
      title { +"World Greeting Service" }
    }
    body {
      h1 { +"Hello, ${req.parent.name}!" }
    }
  }
}
