// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 59 "HTML is just a string, until it is not".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide59

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.hello(req: Greeting.Hello) {
  val response = "<h1>Hello, ${req.parent.name}!</h1>"
  call.respondText(response, contentType = ContentType.Text.Html)
}
