// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 59 "A form is a body too".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide59

import presentation.support.*
import io.ktor.http.Parameters
import io.ktor.server.application.Application
import io.ktor.server.request.receiveParameters
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    post("/greet") {
      val form: Parameters = call.receiveParameters()
      call.respondText("Hello, ${form["name"]}")
    }
  }
}
