// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 62 "Strong types at the edge".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide62

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationCall
import io.ktor.server.plugins.ParameterConversionException
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getOrFail

fun Application.module() {
  routing {
    get("/hello/{hour}") {
      val hour = call.hour("hour")
      call.respondText("Hello, it's ${hour.value} o'clock")
    }
  }
}

@JvmInline value class Hour(val value: Int)

fun ApplicationCall.hour(name: String): Hour {
  val raw = parameters.getOrFail<Int>(name)
  if (raw !in 0..23) throw ParameterConversionException(name, "Hour")
  return Hour(raw)
}
