// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 63 "Control flow is plain Kotlin".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide63

import presentation.support.*
import io.ktor.server.html.respondHtml
import io.ktor.server.routing.RoutingContext
import kotlinx.html.*

suspend fun RoutingContext.spell(req: Spell) {
  call.respondHtml {
    body {
      h1 {
        if (req.name.isEmpty()) {
          +"No name"
        } else {
          +"${req.name.first().uppercaseChar()}"
          req.name.drop(1).forEach { +" - ${it.uppercaseChar()}" }
        }
      }
    }
  }
}
