// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 63 "A delegate knows the property name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide63

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationCall
import io.ktor.server.plugins.ParameterConversionException
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getOrFail
import kotlin.properties.ReadOnlyProperty

fun Application.module() {
  routing {
    get("/hello/{hour}") {
      val hour by call.hour()
      call.respondText("Hello, it's ${hour.value} o'clock")
    }
  }
}

@JvmInline value class Hour(val value: Int)

fun ApplicationCall.hour() = ReadOnlyProperty<Any?, Hour> { _, prop ->
  val raw = parameters.getOrFail<Int>(prop.name)
  if (raw !in 0..23) throw ParameterConversionException(prop.name, "Hour")
  Hour(raw)
}
