// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 66 "Control flow is plain Kotlin".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide66

import presentation.support.*
import io.ktor.server.html.respondHtml
import io.ktor.server.routing.RoutingContext
import kotlinx.html.*

suspend fun RoutingContext.spell(name: String) {
  call.respondHtml {
    body {
      h1 {
        if (name.isEmpty()) {
          +"No name"
        } else {
          +"${name.first().uppercaseChar()}"
          name.drop(1).forEach { +" - ${it.uppercaseChar()}" }
        }
      }
    }
  }
}
