// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 66 "A response is a status and a body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide66

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    post("/greet/{name}") {
      val name = call.parameters["name"]
      if (name !in users) call.respond(HttpStatusCode.NotFound)
      else call.respondText("Hello, $name", status = HttpStatusCode.Created)
    }
  }
}
