// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 68 "The logic does not need Ktor at all".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide68

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  routing {
    get("/greet/{name}/bye") {
      val name: String by call.pathParameters
      call.respondText(bye(name))
    }
    get("/greet/{name}/hello/{hour}") {
      val name: String by call.pathParameters
      val hour: Int by call.pathParameters
      call.respondText(hello(name, hour))
    }
  }
}

fun bye(name: String): String = "Bye, $name"

fun hello(name: String, hour: Int): String = "Hello, $name, it's $hour o'clock"
