// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 68 "Templates are functions".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide68

import presentation.support.*
import io.ktor.server.html.respondHtml
import io.ktor.server.routing.RoutingContext
import kotlinx.html.*

suspend fun RoutingContext.spell(name: String) {
  call.respondHtml {
    body {
      h1 {
        notEmpty(name, emptyMessage = "No name") {
          +"${name.first().uppercaseChar()}"
          name.drop(1).forEach { +" - ${it.uppercaseChar()}" }
        }
      }
    }
  }
}

fun FlowContent.notEmpty(
  value: String,
  emptyMessage: String,
  content: FlowContent.() -> Unit,
) {
  if (value.isEmpty()) +emptyMessage else content()
}
