// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 70 "One plug-in, one line per format".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide70

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.serialization.kotlinx.xml.xml
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation

fun Application.module() {
  install(ContentNegotiation) {
    json()
    xml()
  }
  routes()
}
