// Generated by slidev-theme-kotlin from lessons/lesson-3.md, slide 80 "The handler sees objects, not bytes".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson3.slide80

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Greeting(
  val type: Type = Type.HELLO,
  val name: String,
  @SerialName("tz") val timezone: String? = null,
)

@Serializable
enum class Type {
  @SerialName("hello") HELLO,
  @SerialName("bye") BYE,
}

@Serializable
data class GreetingResponse(val message: String)

fun Application.module() {
  install(ContentNegotiation) { json() }
  routing {
    post("/greet") {
      val greeting = call.receive<Greeting>()
      val message = when (greeting.type) {
        Type.HELLO -> "Hello, ${greeting.name}"
        Type.BYE -> "Bye, ${greeting.name}"
      }
      call.respond(GreetingResponse(message))
    }
  }
}
