// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 28 "The request line is the route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide28

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    get("/hello/{name}") {
      val name = call.parameters["name"]
      val timezone = call.request.queryParameters["timezone"]
      call.respondText("Hello, $name in $timezone")
    }
  }
}
