// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 29 "The request line is the route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide29

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.request.receive
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    post("/greet") {
      val greeting = call.receive<Greeting>()
      call.respondText("Hello, ${greeting.name}")
    }
  }
}
