// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 32 "Configuration is a `@Serializable` data class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide32

import presentation.support.*
import kotlinx.serialization.Serializable

@Serializable
data class Config(
  val host: String,
  val port: Int,
)
