// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 33 "A response is a status and a body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide33

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    post("/greet/{name}") {
      val name = call.parameters["name"]
      if (name !in users) return@post call.respond(HttpStatusCode.NotFound)
      call.respondText("Hello, $name", status = HttpStatusCode.Created)
    }
  }
}
