// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 33 "Configuration is a `@Serializable` data class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide33

import presentation.support.*
import kotlinx.serialization.Serializable

@Serializable
data class Config(
  val host: String,
  val port: Int,
  val environment: Environment,
)

@Serializable
enum class Environment { PROD, STAGING, DEV }
