// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 33 "A file arrives in parts".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide33

import io.ktor.http.content.MultiPartData
import presentation.support.*
import io.ktor.http.content.PartData
import io.ktor.http.content.asFlow
import io.ktor.http.content.forEachPart
import io.ktor.network.sockets.TypeOfService
import io.ktor.server.application.Application
import io.ktor.server.http.content.file
import io.ktor.server.request.receiveMultipart
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import io.ktor.util.cio.writeChannel
import io.ktor.utils.io.copyAndClose
import kotlinx.coroutines.channels.ChannelIterator
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.filterIsInstance
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.map
import kotlinx.html.Entities
import java.io.File

fun Application.module() {
  routing {
    post("/avatar") {
      call.receiveMultipart()
        .forEachPart { part ->
          try {
            if (part is PartData.FileItem) {
              val file = File("uploads/${part.originalFileName ?: "avatar"}")
              part.provider().copyAndClose(file.writeChannel())
            }
          } finally {
            part.release()
          }
        }

      call.respondText("Uploaded")
    }
  }
}

fun MultiPartData.consumeAsFlow(): Flow<PartData> =
  flow {
    while (true) {
      val part = readPart() ?: break
      try {
        emit(part)
      } finally {
        part.release()
      }
    }
  }