// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 34 "A file arrives in parts".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide34

import presentation.support.*
import io.ktor.http.content.PartData
import io.ktor.http.content.forEachPart
import io.ktor.server.application.Application
import io.ktor.server.request.receiveMultipart
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import io.ktor.util.cio.writeChannel
import io.ktor.utils.io.copyAndClose
import java.io.File

fun Application.module() {
  routing {
    post("/avatar") {
      val multipart: MultiPartData = call.receiveMultipart()
      multipart.asFlow()
        .filterIsInstance<PartData.FileItem>()
      
      call.respondText("Uploaded")
    }
  }
}
