// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 35 "Configuration grows by feature".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide35

import presentation.support.*
import kotlinx.serialization.Serializable

@Serializable
data class Config(val server: Server, val github: GitHub)

@Serializable
data class Server(val host: String, val port: Int)

@Serializable
data class GitHub(val token: String)
