// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 36 "A response is a status and a body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide36

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlinx.serialization.Serializable

@Serializable
data class GreetingResponse(val message: String)

fun Application.module() {
  routing {
    post("/greet/{name}") {
      val name = call.parameters["name"]
      if (name !in users) return@post call.respond(HttpStatusCode.NotFound)
      call.respond(HttpStatusCode.Created, GreetingResponse("Hello, $name"))
    }
  }
}
