// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 36 "Load it at runtime with `ApplicationConfig`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide36

import presentation.support.*
import io.ktor.server.config.ApplicationConfig
import io.ktor.server.config.getAs
import kotlinx.serialization.Serializable

@Serializable
data class Config(val host: String, val port: Int)

val config: Config = ApplicationConfig("application.yaml").getAs<Config>()
