// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 37 "Load it at runtime with `ApplicationConfig`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide37

import presentation.support.*
import io.ktor.server.config.ApplicationConfig
import io.ktor.server.config.getAs
import io.ktor.server.config.mergeWith
import kotlinx.serialization.Serializable

@Serializable
data class GitHub(val token: String)

@Serializable
data class Config(val host: String, val port: Int, val github: GitHub)

val config: Config = ApplicationConfig("application.yaml")
  .mergeWith(ApplicationConfig("github.yaml"))
  .getAs<Config>()
