// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 38 "Load the config first, then start the server".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide38

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.config.ApplicationConfig
import io.ktor.server.config.getAs
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty
import kotlinx.serialization.Serializable

@Serializable
data class Config(val server: Server, val github: GitHub)

@Serializable
data class Server(val host: String, val port: Int)

@Serializable
data class GitHub(val token: String)

fun Application.module(config: Config) {
  routes()
}

fun main() {
  val config = ApplicationConfig("application.yaml").getAs<Config>()
  embeddedServer(
    Netty,
    host = config.server.host,
    port = config.server.port,
  ) { module(config) }.start(wait = true)
}
