// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 39 "Secrets never live in the source".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide39

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.defaultRequest
import io.ktor.client.request.bearerAuth

val token = "ghp_sup3rs3cret"

val client = HttpClient(CIO) {
  defaultRequest { bearerAuth(token) }
}
