// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 40 "Secrets never live in the source".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide40

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.defaultRequest
import io.ktor.client.request.bearerAuth
import io.ktor.server.config.ApplicationConfig
import io.ktor.server.config.getAs
import kotlinx.serialization.Serializable

@Serializable
data class Config(val github: GitHub)

@Serializable
data class GitHub(val token: String)

val config = ApplicationConfig("application.yaml").getAs<Config>()

val client = HttpClient(CIO) {
  defaultRequest { bearerAuth(config.github.token) }
}
