// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 40 "A response is a status and a body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide40

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlinx.serialization.Serializable

fun interface UserService {
  operator fun contains(name: String?): Boolean
}

@Serializable data class GreetingResponse(val message: String)

fun Application.module(users: UserService) {
  routing {
    post("/greet/{name}") {
      val name = call.parameters["name"]
      if (name !in users) call.respond(HttpStatusCode.NotFound)
      else call.respond(HttpStatusCode.Created, GreetingResponse("Hello, $name"))
    }
  }
}
