// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 41 "`EngineMain` reads a file instead".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide41

import presentation.support.*

fun main(args: Array<String>): Unit =
  io.ktor.server.netty.EngineMain.main(args)
