// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 41 "`@Serializable` derives the code".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide41

import presentation.support.*
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Greeting(
  val type: Type = Type.HELLO,
  val name: String,
  @SerialName("tz") val timezone: String? = null,
)

@Serializable
enum class Type {
  @SerialName("hello") HELLO,
  @SerialName("bye") BYE,
}
