// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 45 "`@Serializable` derives the code".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide45

import presentation.support.*
import kotlinx.serialization.Serializable

@Serializable
data class Greeting(
  val type: Type,
  val name: String,
  val timezone: String,
)

enum class Type { HELLO, BYE }
