// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 46 "The module reads its own keys".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide46

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.config.property
import kotlinx.serialization.Serializable

@Serializable
data class GitHub(val token: String)

fun Application.module() {
  val github: GitHub = property("github")
  routes()
}
