// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 47 "The module reads its own keys".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide47

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.annotations.Property
import kotlinx.serialization.Serializable

@Serializable
data class GitHub(val token: String)

fun Application.module(@Property("github") github: GitHub) {
  routes()
}
