// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 48 "DTOs are not the domain model".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide48

import presentation.support.*
import kotlinx.datetime.TimeZone
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class Type {
  @SerialName("hello") HELLO,
  @SerialName("bye") BYE,
}

@Serializable
data class Greeting(
  val type: Type = Type.HELLO,
  val name: String,
  @SerialName("tz") val timezone: String? = null,
)

class Recipient(val name: String, val timezone: TimeZone)

fun Greeting.recipient(): Recipient =
  Recipient(name, timezone?.let(TimeZone::of) ?: TimeZone.UTC)
