// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 49 "`embeddedServer` can carry a configuration".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide49

import presentation.support.*
import io.ktor.server.config.ApplicationConfig
import io.ktor.server.engine.applicationEnvironment
import io.ktor.server.engine.connector
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main() {
  embeddedServer(
    Netty,
    environment = applicationEnvironment {
      config = ApplicationConfig("application.yaml")
    },
    configure = { connector { port = 8080 } },
  ) { module() }.start(wait = true)
}
