// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 50 "A `KSerializer` is a descriptor and two functions".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide50

import presentation.support.*
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerializationException
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = NameSerializer::class)
class Name private constructor(val value: String) {
  companion object {
    fun of(raw: String): Name? = raw.trim().ifBlank { null }?.let(::Name)
  }
}

object NameSerializer : KSerializer<Name> {
  override val descriptor =
    PrimitiveSerialDescriptor("Name", PrimitiveKind.STRING)
  override fun serialize(encoder: Encoder, value: Name) =
    encoder.encodeString(value.value)
  override fun deserialize(decoder: Decoder): Name =
    Name.of(decoder.decodeString())
      ?: throw SerializationException("name is blank")
}
