// Generated by slidev-theme-kotlin from lessons/lesson-2.md, slide 51 "Dates and times are ISO 8601 strings".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson2.slide51

import presentation.support.*
import kotlin.time.Instant
import kotlinx.datetime.LocalDateTime
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Talk(
  val title: String,
  val startsAt: LocalDateTime,
  @SerialName("tz") val timezone: String,
  val createdAt: Instant,
)
