// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 111 "WebSockets are a plug-in".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide111

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.websocket.WebSockets

fun Application.module() {
  install(WebSockets)
  routes()
}
