// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 112 "A handler loops over `incoming`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide112

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.routing.routing
import io.ktor.server.websocket.webSocket
import io.ktor.websocket.Frame
import io.ktor.websocket.readText
import io.ktor.websocket.send

fun Application.routes() {
  routing {
    webSocket("/greet") {
      for (frame in incoming) {
        when (frame) {
          is Frame.Text -> send("Hello, ${frame.readText()}")
          else -> {}
        }
      }
    }
  }
}
