// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 116 "Typed frames are read one at a time".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide116

import presentation.support.*
import io.ktor.server.routing.Route
import io.ktor.server.websocket.receiveDeserialized
import io.ktor.server.websocket.sendSerialized
import io.ktor.server.websocket.webSocket

fun Route.greet() {
  webSocket("/greet") {
    while (true) {
      val req = receiveDeserialized<Request>()
      sendSerialized(Response("Hello, ${req.name}"))
    }
  }
}
