// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 127 "JSON frames need a converter".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide127

import presentation.support.*
import io.ktor.serialization.kotlinx.KotlinxWebsocketSerializationConverter
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.websocket.WebSockets
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable data class Request(val name: String)
@Serializable data class Response(val greeting: String)

fun Application.module() {
  install(WebSockets) {
    contentConverter = KotlinxWebsocketSerializationConverter(Json)
  }
  routes()
}
