// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 129 "A request is a verb and a URL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide129

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.request.get

suspend fun HttpClient.github(user: String) {
  val response = get("/users/$user")
}
