// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 130 "Typed frames are read one at a time".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide130

import presentation.support.*
import io.ktor.server.routing.Route
import io.ktor.server.websocket.receiveDeserialized
import io.ktor.server.websocket.sendSerialized
import io.ktor.server.websocket.webSocket
import io.ktor.websocket.CloseReason
import io.ktor.websocket.close
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.ClosedReceiveChannelException

fun Route.greet() {
  webSocket("/greet") {
    try {
      while (true) {
        val req = receiveDeserialized<Request>()
        sendSerialized(Response("Hello, ${req.name}"))
      }
    } catch (e: ClosedReceiveChannelException) {
      // the client closed the socket
    } catch (e: CancellationException) {
      close(CloseReason(CloseReason.Codes.GOING_AWAY, "Shutting down"))
      throw e
    }
  }
}
