// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 130 "A request is a verb and a URL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide130

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode

suspend fun HttpClient.github(user: String) {
  val response = get("/users/$user")
  when (response.status) {
    HttpStatusCode.OK -> response.body<User>()
    else -> TODO()
  }
}
