// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 131 "The request block carries the body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide131

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.contentType

suspend fun HttpClient.describe(owner: String, repo: String, text: String) {
  post("/repos/$owner/$repo") {
    contentType(ContentType.Application.Json)
    setBody(mapOf("description" to text))
  }
}
