// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 132 "The client suspends, so does the handler".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide132

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.request.get

suspend fun HttpClient.github(user: String) {
  get("/users/$user")
}
