// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 132 "Server-Sent Events go one way".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide132

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.routing.routing
import io.ktor.server.sse.SSE
import io.ktor.server.sse.sse
import io.ktor.sse.ServerSentEvent
import kotlinx.coroutines.delay

fun Application.module() {
  install(SSE)
  routing {
    sse("/countdown") {
      for (n in 10 downTo 1) {
        send(ServerSentEvent("$n"))
        delay(1000)
      }
    }
  }
}
