// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 134 "Concurrent requests share a scope".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide134

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope

suspend fun HttpClient.github(user: String): Profile = coroutineScope {
  val info = async { get("/users/$user").body<User>() }
  val repos = async { get("/users/$user/repos").body<List<Repo>>() }
  Profile(info.await(), repos.await())
}
