// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 138 "A service is an interface".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide138

import presentation.support.*

interface GitHubService {
  suspend fun getUserInfo(user: String): User?
  suspend fun getUserRepos(user: String): List<Repo>?
}
