// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 140 "Handlers depend on the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide140

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.Routing
import io.ktor.server.routing.get
import io.ktor.server.util.getValue
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope

fun Routing.profile(github: GitHubService) {
  get("/profile") {
    val user: String by call.queryParameters
    coroutineScope {
      val info = async { github.getUserInfo(user) }
      val repos = async { github.getUserRepos(user) }
      when (val found = info.await()) {
        null -> call.respond(HttpStatusCode.NotFound)
        else -> call.respond(Profile(found, repos.await().orEmpty()))
      }
    }
  }
}
