// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 142 "The implementation owns the client".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide142

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode

class GitHubHttp(private val client: HttpClient) : GitHubService {
  override suspend fun getUserInfo(user: String): User? {
    val response = client.get("/users/$user")
    return if (response.status == HttpStatusCode.OK) response.body<User>()
    else null
  }

  override suspend fun getUserRepos(user: String): List<Repo>? =
    client.get("/users/$user/repos")
      .takeIf { it.status == HttpStatusCode.OK }
      ?.body<List<Repo>>()
}
