// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 143 "Dependencies share the `Application` lifecycle".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide143

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStopped

fun Application.client(): HttpClient {
  val client = HttpClient()
  monitor.subscribe(ApplicationStopped) { client.close() }
  return client
}
