// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 144 "Wire the graph by hand".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide144

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStopped
import io.ktor.server.routing.routing

fun Application.client(): HttpClient {
  val client = HttpClient()
  monitor.subscribe(ApplicationStopped) { client.close() }
  return client
}

class Dependencies(val github: GitHubService)

fun Application.dependencies(): Dependencies =
  Dependencies(github = GitHubHttp(client()))

fun Application.module() {
  val dependencies = dependencies()
  routing { profile(dependencies.github) }
}
