// Generated by slidev-theme-kotlin from lessons/lesson-6.md, slide 145 "The DI plug-in provides the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson6.slide145

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.dependencies
import io.ktor.server.plugins.di.resolve

fun Application.module() {
  dependencies {
    provide { HttpClient() }
    provide<GitHubService> { GitHubHttp(resolve<HttpClient>()) }
  }
}
