// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 92 "The remote API is a set of resources".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide92

import presentation.support.*
import io.ktor.resources.Resource
import kotlinx.serialization.Serializable

object GitHub {
  @Serializable
  @Resource("/users/{username}")
  class User(val username: String) {
    @Serializable
    @Resource("repos")
    class Repos(val user: User)
  }

  @Serializable
  @Resource("/repos/{owner}/{repo}")
  class Repo(val owner: String, val repo: String)
}
