// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 95 "Requests are resource instances".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide95

import presentation.support.*
import io.ktor.client.plugins.resources.get
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.github(user: String) {
  client().use { client ->
    val response = client.get(GitHub.User(user))
  }
}
