// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 95 "A request is a verb and a URL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide95

import presentation.support.*
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.github(user: String) {
  client().use { client ->
    val response = client.get("/users/$user")
    when (response.status) {
      HttpStatusCode.OK -> call.respond(response.body<User>())
      else -> call.respond(HttpStatusCode.NotFound)
    }
  }
}
