// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 96 "A request is a verb and a URL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide96

import presentation.support.*
import io.ktor.client.request.get
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.github(user: String) {
  client().use { client ->
    val response = client.get("/users/$user")
  }
}
