// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 99 "The client suspends, so does the handler".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide99

import presentation.support.*
import io.ktor.client.request.get
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.github(user: String) {
  client().use { client -> client.get("/users/$user") }
}
