// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 99 "Concurrent requests share a scope".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide99

import presentation.support.*
import io.ktor.client.call.body
import io.ktor.client.plugins.resources.get
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope

suspend fun RoutingContext.github(user: String) = coroutineScope {
  client().use { client ->
    val resource = GitHub.User(user)
    val (info, repos) = awaitAll(
      async { client.get(resource) },
      async { client.get(GitHub.User.Repos(resource)) },
    )
    call.respond(Profile(info.body<User>(), repos.body<List<Repo>>()))
  }
}
