// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 101 "Retries are a client plug-in".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide101

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.engine.cio.CIO
import io.ktor.client.plugins.HttpRequestRetry
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.plugins.defaultRequest
import io.ktor.serialization.kotlinx.json.json
import kotlinx.serialization.json.Json

fun client(): HttpClient = HttpClient(CIO) {
  install(ContentNegotiation) {
    json(Json { ignoreUnknownKeys = true })
  }
  defaultRequest { url("https://api.github.com") }
  install(HttpRequestRetry) {
    retryOnServerErrors(maxRetries = 5)
    constantDelay(millis = 1000)
  }
}
