// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 101 "The schema is a `@Serializable` class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide101

import presentation.support.*
import kotlinx.serialization.Serializable

@Serializable
data class User(
  val name: String?,
  val bio: String?,
  @SerialName("avatar_url") val avatarUrl: String?,
)

@Serializable
data class Repo(
  val name: String,
  val description: String?,
  val fork: Boolean,
  @SerialName("stargazers_count") val stargazersCount: Int,
)
