// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 103 "A request is a verb and a URL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide103

import presentation.support.*
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext

suspend fun HttpClient.github(user: String) {
  val response = get("/users/$user")
  when (response.status) {
    HttpStatusCode.OK -> response.body<User>()
    else -> TODO()
  }
}
