// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 104 "The request block carries the body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide104

import presentation.support.*
import io.ktor.client.request.post
import io.ktor.client.request.setBody
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.http.contentType
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext

suspend fun HttpClient.describe(owner: String, repo: String, text: String) {
    client.post("/repos/$owner/$repo") {
      contentType(ContentType.Application.Json)
      setBody(mapOf("description" to text))
    }
}
