// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 105 "The client suspends, so does the handler".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide105

import presentation.support.*
import io.ktor.client.request.get
import io.ktor.server.routing.RoutingContext

suspend fun HttpClient.github(user: String) {
  get("/users/$user")
}
