// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 105 "The DI plug-in provides the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide105

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.dependencies

fun Application.module() {
  dependencies {
    provide<GitHubService> { GitHubHttp(client()) }
  }
  routes()
}
