// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 107 "Blocking code goes to `Dispatchers.IO`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide107

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.server.response.respondBytes
import io.ktor.server.routing.RoutingContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

suspend fun RoutingContext.avatar(name: String) {
  val bytes = withContext(Dispatchers.IO) {
    File("uploads/$name.png").readBytes()
  }
  call.respondBytes(bytes, ContentType.Image.PNG)
}
