// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 107 "Concurrent requests share a scope".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide107

import presentation.support.*
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope

suspend fun HttpClient.github(user: String) = coroutineScope {
    val info = async { client.get("/users/$user").body<User>() }
    val repos = async { client.get("/users/$user/repos").body<List<Repo>>() } 
    call.respond(Profile(info.await(), repos.await()))
}
