// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 109 "The DI plug-in provides the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide109

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.dependencies
import io.ktor.server.plugins.di.resolve
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

suspend fun Application.module() {
  dependencies {
    provide<GitHubService> { GitHubHttp(client()) }
  }
  routes()
}

suspend fun Application.routes() {
  val github: GitHubService = dependencies.resolve()
  routing {
    get("/github/{username}") {
      val username: String by call.pathParameters
      github(github, username)
    }
  }
}
