// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 109 "Concurrent requests share a scope".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide109

import presentation.support.*
import io.ktor.client.call.body
import io.ktor.client.request.get
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.coroutineScope

suspend fun RoutingContext.github(user: String) = coroutineScope {
  client().use { client ->
    val (info, repos) = awaitAll(
      async { client.get("/users/$user") },
      async { client.get("/users/$user/repos") },
    )
    call.respond(Profile(info.body<User>(), repos.body<List<Repo>>()))
  }
}
