// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 111 "Session data is plain text by default".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide111

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.sessions.Sessions
import io.ktor.server.sessions.cookie
import kotlinx.serialization.Serializable

@Serializable
data class GreetingTracker(val greetings: Set<String>)

fun Application.module() {
  install(Sessions) {
    cookie<GreetingTracker>("track")
  }
  routes()
}
