// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 111 "A service is an interface".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide111

import presentation.support.*

interface GitHubService {
  suspend fun getUserInfo(user: String): User?
  suspend fun getUserRepos(user: String): List<Repo>?
}
