// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 112 "A service is an interface".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide112

import presentation.support.*

sealed interface CreateRepoResult

data class Succces(val repo: Repo): CreateRepoResult

data object UserNotFound : CreateRepoResult

data object RepoAlreadyExists : CreateRepoResult

interface GitHubService {
  suspend fun getUserInfo(user: String): User?
  suspend fun getUserRepos(user: String): List<Repo>?
  suspend fun createRepo(user: String, repo: String): CreateRepoResult
}
