// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 114 "Handlers depend on the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide114

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext
import kotlinx.coroutines.async
import kotlinx.coroutines.coroutineScope

suspend fun RoutingContext.github(github: GitHubService, user: String) =
  coroutineScope {
    val info = async { github.getUserInfo(user) }
    val repos = async { github.getUserRepos(user) }
    when (val found = info.await()) {
      null -> call.respond(HttpStatusCode.NotFound)
      else -> call.respond(Profile(found, repos.await().orEmpty()))
    }
  }
