// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 115 "A folder is a route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide115

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.http.content.CompressedFileType
import io.ktor.server.http.content.staticFiles
import io.ktor.server.routing.routing
import java.io.File

fun Application.module() {
  routing {
    staticFiles("/assets", File("files")) {
      default("index.html")
      preCompressed(CompressedFileType.GZIP)
      exclude { file -> file.name.startsWith(".") }
    }
  }
}
