// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 115 "Dependencies share the `Application` lifecycle".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide115

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStopped

fun Application.gitHub(): GitHubService {
  val github = GitHubHttp(client())
  monitor.subscribe(ApplicationStopped) { github.close() }
  return github
}
