// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 116 "Wire the graph by hand".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide116

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStopped
import io.ktor.server.routing.routing

fun Application.gitHub(): GitHubService {
  val github = GitHubHttp(client())
  monitor.subscribe(ApplicationStopped) { github.close() }
  return github
}

class Dependencies(val github: GitHubService)

fun Application.dependencies(): Dependencies =
  Dependencies(github = gitHub())

fun Application.module() {
  val dependencies = dependencies()
  routing { profile(dependencies.github) }
}
