// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 117 "A single page app is one file and many assets".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide117

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.http.content.react
import io.ktor.server.http.content.singlePageApplication
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    singlePageApplication {
      useResources = true
      react("app")
    }
  }
}
