// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 118 "The DI plug-in provides the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide118

import io.ktor.client.HttpClient
import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.dependencies
import io.ktor.server.routing.routing

fun Application.module() {
  dependencies {
    provide { HttpClient() }
    provide<GitHubService> { GitHubHttp(resolve<HttpClient>()) }
  }
  val github: GitHubService by dependencies
  routing { profile(github) }
}
