// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 118 "Compression is one line".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide118

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.compression.Compression

fun Application.module() {
  install(Compression)
  routes()
}
