// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 119 "The DI plug-in provides the service".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide119

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.dependencies
import io.ktor.server.plugins.di.resolve
import io.ktor.server.routing.routing

suspend fun Application.module() {
  dependencies {
    provide<GitHubService> { GitHubHttp(client()) }
  }
  routes()
}

suspend fun Application.routes() {
  val github: GitHubService = dependencies.resolve()
  routing { profile(github) }
}
