// Generated by slidev-theme-kotlin from lessons/lesson-5.md, slide 121 "CORS is opt-in, by the server".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson5.slide121

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.cors.routing.CORS

fun Application.module() {
  install(CORS) {
    allowHost(
      "example.com",
      schemes = listOf("https"),
      subDomains = listOf("www", "app"),
    )
  }
  routes()
}
