// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 136 "The message is not for the client".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide136

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.html.respondHtml
import io.ktor.server.plugins.statuspages.StatusPages
import kotlinx.html.body
import kotlinx.html.h1
import kotlinx.html.p

fun Application.module() {
  install(StatusPages) {
    exception<Throwable> { call, cause ->
      call.respondHtml(HttpStatusCode.InternalServerError) {
        body {
          h1 { +"This is embarrassing" }
          cause.message?.let { p { +it } }
        }
      }
    }
  }
  routes()
}
