// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 138 "A plug-in hooks into the pipeline".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide138

import presentation.support.*
import io.ktor.server.application.createApplicationPlugin
import io.ktor.server.application.hooks.CallFailed

val MyPlugin = createApplicationPlugin("MyPlugin") {
  onCallReceive { call -> TODO() }
  onCallRespond { call -> TODO() }
  on(CallFailed) { call, cause -> TODO() }
}
