// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 139 "Narrow the exception, log the detail".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide139

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.html.respondHtml
import io.ktor.server.plugins.statuspages.StatusPages
import kotlinx.html.body
import kotlinx.html.h1

context(logger: Logger)
fun Application.module() {
  install(StatusPages) {
    exception<DatabaseException> { call, cause ->
      logger.log("db: ${cause.message}")
      call.respondHtml(HttpStatusCode.InternalServerError) {
        body { h1 { +"This is embarrassing" } }
      }
    }
  }
  routes()
}
