// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 140 "`StatusPages` rewrites the response".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide140

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.html.respondHtml
import io.ktor.server.plugins.statuspages.StatusPages
import kotlinx.html.body
import kotlinx.html.h1

fun Application.module() {
  install(StatusPages) {
    status(HttpStatusCode.NotFound) { call, status ->
      call.respondHtml(status) {
        body { h1 { +"Keep looking somewhere else" } }
      }
    }
  }
  routes()
}
