// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 147 "The test is only the test".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide147

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.ktor.client.plugins.resources.get
import io.ktor.http.HttpStatusCode
import org.junit.jupiter.api.Test

@Test
fun bye() = appTest { client ->
  client.get(Greeting.Bye("alex")).status shouldBe HttpStatusCode.OK
}
