// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 147 "A marker object stands for a page".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide147

import presentation.support.*
import io.ktor.server.response.respond
import io.ktor.server.routing.RoutingContext
import kotlinx.serialization.Serializable

@Serializable
object SayPlease

suspend fun RoutingContext.please() {
  call.respond(SayPlease)
}
