// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 148 "Generated input finds the corner cases".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide148

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.kotest.property.Arb
import io.kotest.property.arbitrary.string
import io.kotest.property.checkAll
import io.ktor.client.plugins.resources.get
import io.ktor.http.HttpStatusCode
import org.junit.jupiter.api.Test

@Test
fun anyName() = appTest { client ->
  checkAll(Arb.string()) { name ->
    client.get(Greeting.Bye(name)).status shouldBe HttpStatusCode.OK
  }
}
