// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 151 "WebSockets are a plug-in".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide151

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.websocket.WebSockets

fun Application.module() {
  install(WebSockets)
  routes()
}
