// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 153 "Installation order is execution order".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide153

import presentation.support.*
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation

fun Application.module() {
  install(FourOhFour)
  install(ContentNegotiation) {
    json()
  }
  routes()
}
