// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 153 "Validation is a plug-in".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide153

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.requestvalidation.RequestValidation
import io.ktor.server.plugins.requestvalidation.ValidationResult

fun Application.module() {
  install(RequestValidation) {
    validate<Greeting> { greeting ->
      if (greeting.name.isBlank()) ValidationResult.Invalid("name is blank")
      else ValidationResult.Valid
    }
  }
  routes()
}
