// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 154 "A plug-in can be scoped to a route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide154

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.requestvalidation.RequestValidation
import io.ktor.server.plugins.requestvalidation.ValidationResult
import io.ktor.server.request.receive
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.route
import io.ktor.server.routing.routing

fun Application.module() {
  routing {
    route("/greet") {
      install(RequestValidation) {
        validate<Greeting> { greeting ->
          if (greeting.name.isBlank()) ValidationResult.Invalid("name is blank")
          else ValidationResult.Valid
        }
      }
      post {
        call.respondText("Hello, ${call.receive<Greeting>().name}")
      }
    }
  }
}
