// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 154 "A failed validation is a `400`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide154

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.requestvalidation.RequestValidation
import io.ktor.server.plugins.requestvalidation.RequestValidationException
import io.ktor.server.plugins.requestvalidation.ValidationResult
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.response.respond

fun Application.module() {
  install(RequestValidation) {
    validate<Greeting> { greeting ->
      if (greeting.name.isBlank()) ValidationResult.Invalid("name is blank")
      else ValidationResult.Valid
    }
  }
  install(StatusPages) {
    exception<RequestValidationException> { call, cause ->
      call.respond(HttpStatusCode.BadRequest, cause.reasons.joinToString())
    }
  }
  routes()
}
