// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 155 "The test is only the test".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide155

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import org.junit.jupiter.api.Test

@Test
fun bye() = appTest { client ->
  client.get("/greet/alex/bye").status shouldBe HttpStatusCode.OK
}
