// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 158 "Timers carry your tags".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide158

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.metrics.micrometer.MicrometerMetrics
import io.micrometer.prometheusmetrics.PrometheusConfig
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry

val prometheus = PrometheusMeterRegistry(PrometheusConfig.DEFAULT)

fun Application.module() {
  install(MicrometerMetrics) {
    registry = prometheus
    timers { call, throwable ->
      tag("premium", call.request.headers["X-Premium"] ?: "no")
    }
  }
  routes()
}
