// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 159 "`transformBody` swaps the body".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide159

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.http.HttpStatusCode
import io.ktor.http.content.TextContent
import io.ktor.http.withCharset
import io.ktor.server.application.createApplicationPlugin
import kotlinx.html.body
import kotlinx.html.h1
import kotlinx.html.html
import kotlinx.html.stream.createHTML

val FourOhFour = createApplicationPlugin("FourOhFour") {
  onCallRespond { call ->
    transformBody { body ->
      when (body) {
        is SayPlease -> TextContent(
          text = createHTML().html { body { h1 { +"Say please" } } },
          contentType = ContentType.Text.Html.withCharset(Charsets.UTF_8),
          status = HttpStatusCode.Forbidden,
        )
        else -> body
      }
    }
  }
}
