// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 161 "Metrics are a plug-in with a registry".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide161

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.metrics.micrometer.MicrometerMetrics
import io.micrometer.prometheusmetrics.PrometheusConfig
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry

val prometheus = PrometheusMeterRegistry(PrometheusConfig.DEFAULT)

fun Application.module() {
  install(MicrometerMetrics) {
    registry = prometheus
  }
  routes()
}
