// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 164 "Metrics are a plug-in with a registry".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide164

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.metrics.micrometer.MicrometerMetrics
import io.ktor.server.response.respond
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.micrometer.prometheusmetrics.PrometheusConfig
import io.micrometer.prometheusmetrics.PrometheusMeterRegistry

val prometheus = PrometheusMeterRegistry(PrometheusConfig.DEFAULT)

fun Application.module() {
  install(MicrometerMetrics) {
    registry = prometheus
  }
  routing {
    get("/metrics") { call.respond(prometheus.scrape()) }
  }
  routes()
}
