// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 165 "A comment documents the route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide165

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.response.respond
import io.ktor.server.routing.Route
import io.ktor.server.routing.get
import io.ktor.server.util.getValue

fun Route.greeting() {
  /**
   * Greet a person by name.
   * Path: name [String] the person to greet
   * Response: 400 The name is missing.
   * Response: 200 [GreetingResponse] The greeting.
   */
  get("/greet/{name}") {
    val name: String by call.parameters
    call.respond(GreetingResponse("Hello, $name"))
  }
}
