// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 166 "`describe` documents at runtime".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide166

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.openapi.jsonSchema
import io.ktor.server.routing.Route
import io.ktor.server.routing.get
import io.ktor.server.routing.openapi.describe
import io.ktor.utils.io.ExperimentalKtorApi

@OptIn(ExperimentalKtorApi::class)
fun Route.greeting(): Route =
  get("/greet/{name}") { greet() }.describe {
    summary = "Greet a person by name"
    parameters {
      query("lang") { description = "Language of the greeting" }
    }
    responses {
      HttpStatusCode.OK {
        description = "The greeting"
        schema = jsonSchema<GreetingResponse>()
      }
    }
  }
