// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 166 "Generated input finds the corner cases".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide166

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.kotest.property.Arb
import io.kotest.property.arbitrary.string
import io.kotest.property.checkAll
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import io.ktor.http.encodeURLPathPart
import org.junit.jupiter.api.Test

@Test
fun anyName() = appTest { client ->
  checkAll(Arb.string()) { name ->
    val response = client.get("/greet/${name.encodeURLPathPart()}/bye")
    response.status shouldBe HttpStatusCode.OK
  }
}
