// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 167 "Two routes serve the document".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide167

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.openapi.OpenApiInfo
import io.ktor.server.application.Application
import io.ktor.server.plugins.openapi.openAPI
import io.ktor.server.routing.openapi.OpenApiDocSource
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    openAPI("/openapi") {
      info = OpenApiInfo("Greeting API", "1.0.0")
      source = OpenApiDocSource.Routing(ContentType.Application.Json)
    }
  }
}
