// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 168 "`CallLogging` writes one line per request".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide168

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.calllogging.CallLogging
import io.ktor.server.request.path
import org.slf4j.event.Level

fun Application.module() {
  install(CallLogging) {
    level = Level.INFO
    filter { call -> !call.request.path().startsWith("/metrics") }
  }
  routes()
}
