// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 168 "Other services are mocked in the test".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide168

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.application.install
import io.ktor.server.plugins.contentnegotiation.ContentNegotiation as ServerContentNegotiation
import io.ktor.server.response.respond
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.testing.testApplication
import org.junit.jupiter.api.Test

@Test
fun profile() = testApplication {
  externalServices {
    hosts("https://api.github.com") {
      install(ServerContentNegotiation) { json() }
      routing { get("/users/{u}") { call.respond(User("Alex", null, null)) } }
    }
  }
  application { module(GitHubHttp(client())) }
  client.get("/github/alex").status shouldBe HttpStatusCode.OK
}
