// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 169 "Two routes serve the document".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide169

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.openapi.OpenApiInfo
import io.ktor.server.application.Application
import io.ktor.server.plugins.openapi.openAPI
import io.ktor.server.plugins.swagger.swaggerUI
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.openapi.OpenApiDocSource
import io.ktor.server.routing.openapi.hide
import io.ktor.server.routing.routing
import io.ktor.utils.io.ExperimentalKtorApi

@OptIn(ExperimentalKtorApi::class)
fun Application.routes() {
  routing {
    openAPI("/openapi") {
      info = OpenApiInfo("Greeting API", "1.0.0")
      source = OpenApiDocSource.Routing(ContentType.Application.Json)
    }
    swaggerUI("/swagger") {
      info = OpenApiInfo("Greeting API", "1.0.0")
      source = OpenApiDocSource.Routing(ContentType.Application.Json)
      remotePath = "openapi.json"
    }
    get("/health") { call.respondText("ok") }.hide()
  }
}
