// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 170 "The service is tested without a server".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide170

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.ktor.client.HttpClient
import io.ktor.client.engine.mock.MockEngine
import io.ktor.client.engine.mock.respond
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.plugins.defaultRequest
import io.ktor.http.HttpHeaders
import io.ktor.http.headersOf
import io.ktor.serialization.kotlinx.json.json
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test

@Test
fun userInfo() = runTest {
  val engine = MockEngine { request ->
    respond(
      content = """{"name": "Alex", "bio": null, "avatar_url": null}""",
      headers = headersOf(HttpHeaders.ContentType, "application/json"),
    )
  }
  val client = HttpClient(engine) {
    install(ContentNegotiation) { json() }
    defaultRequest { url("https://api.github.com") }
  }
  GitHubHttp(client).getUserInfo("alex")?.name shouldBe "Alex"
}
