// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 175 "Your own counters use the same registry".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide175

import presentation.support.*
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext
import io.micrometer.core.instrument.MeterRegistry

suspend fun RoutingContext.bye(registry: MeterRegistry, name: String) {
  registry.counter("bye").increment()
  call.respondText("Bye, $name")
}
