// Generated by slidev-theme-kotlin from lessons/lesson-7.md, slide 179 "`CallId` correlates the lines".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson7.slide179

import presentation.support.*
import io.ktor.http.HttpHeaders
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.callid.CallId
import io.ktor.server.plugins.callid.callIdMdc
import io.ktor.server.plugins.callid.generate
import io.ktor.server.plugins.calllogging.CallLogging
import io.ktor.server.request.path
import org.slf4j.event.Level

fun Application.module() {
  install(CallId) {
    header(HttpHeaders.XRequestId)
    generate(length = 12)
  }
  install(CallLogging) {
    level = Level.INFO
    filter { call -> !call.request.path().startsWith("/metrics") }
    callIdMdc("call-id")
  }
  routes()
}
