// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 75 "A session is a registered class".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide75

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.sessions.SessionStorageMemory
import io.ktor.server.sessions.Sessions
import io.ktor.server.sessions.cookie
import io.ktor.server.sessions.header
import kotlinx.serialization.Serializable

@Serializable
data class GreetingTracker(val greetings: Set<String>)

@Serializable
data class SecretInfo(val secret: String)

fun Application.module() {
  install(Sessions) {
    cookie<GreetingTracker>("track")
    header<SecretInfo>("secret", SessionStorageMemory())
  }
  routes()
}
