// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 75 "Session data is plain text by default".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide75

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.sessions.SessionTransportTransformerEncrypt
import io.ktor.server.sessions.Sessions
import io.ktor.server.sessions.cookie
import io.ktor.util.hex
import kotlinx.serialization.Serializable

@Serializable
data class GreetingTracker(val greetings: Set<String>)

val encryptKey = hex("00112233445566778899aabbccddeeff")

val signKey = hex("6819b57a326945c1968f45236589")

fun Application.module() {
  install(Sessions) {
    cookie<GreetingTracker>("track") {
      cookie.path = "/"
      transform(SessionTransportTransformerEncrypt(encryptKey, signKey))
    }
  }
  routes()
}
