// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 79 "A folder is a route".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide79

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.http.content.staticFiles
import io.ktor.server.http.content.staticResources
import io.ktor.server.routing.routing
import java.io.File

fun Application.module() {
  routing {
    staticFiles("/uploads", File("uploads"))
    staticResources("/assets", "static")
  }
}
