// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 83 "The handler reads and writes the session".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide83

import presentation.support.*
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext
import io.ktor.server.sessions.get
import io.ktor.server.sessions.sessions
import io.ktor.server.sessions.set
import kotlinx.serialization.Serializable

@Serializable
data class GreetingTracker(val greetings: Set<String>)

suspend fun RoutingContext.hello(name: String) {
  val previous = call.sessions.get<GreetingTracker>()?.greetings.orEmpty()
  call.sessions.set(GreetingTracker(previous + "hello"))
  if ("bye" in previous) {
    call.respondText("I thought you were gone, $name")
  } else {
    call.respondText("Hello, $name")
  }
}
