// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 85 "CORS is opt-in, by the server".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide85

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.cors.routing.CORS

fun Application.module() {
  install(CORS) {
    anyHost()
  }
  routes()
}
