// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 85 "The property name is the key".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide85

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  routing {
    get("/bye/{name}") {
      val name: String by call.pathParameters
      call.respondText("Bye, $name")
    }
    get("/hello/{name}/{hour}") {
      val name = call.parameters["name"]
      val hour = call.parameters["hour"]?.toInt()
      call.respondText("Hello, $name, it's $hour o'clock")
    }
  }
}
