// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 94 "Handlers are extensions of `RoutingContext`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide94

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  routing {
    get("/greet/{name}/bye") { bye() }
    get("/greet/{name}/hello/{hour}") { hello() }
  }
}

suspend fun RoutingContext.bye() {
  val name: String by call.pathParameters
  call.respondText("Bye, $name")
}

suspend fun RoutingContext.hello() {
  val name: String by call.pathParameters
  val hour: Int by call.pathParameters
  call.respondText("Hello, $name, it's $hour o'clock")
}
