// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 96 "HTML is just a string, until it is not".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide96

import presentation.support.*
import io.ktor.http.ContentType
import io.ktor.server.response.respondText
import io.ktor.server.routing.RoutingContext

suspend fun RoutingContext.hello(name: String) {
  val response = "<h1>Hello, $name!</h1>"
  call.respondText(response, contentType = ContentType.Text.Html)
}
