// Generated by slidev-theme-kotlin from lessons/lesson-4.md, slide 98 "HTML is a Kotlin DSL".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson4.slide98

import presentation.support.*
import io.ktor.server.html.respondHtml
import io.ktor.server.routing.RoutingContext
import kotlinx.html.*

suspend fun RoutingContext.hello(name: String) {
  call.respondHtml {
    head {
      title { +"World Greeting Service" }
    }
    body {
      h1 { +"Hello, $name!" }
    }
  }
}
