// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 164 "Providers are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide164

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.Authentication
import io.ktor.server.auth.basic

fun Application.module() {
  install(Authentication) {
    basic("auth") {
      realm = "Access to secrets"
    }
  }
  routes()
}
