// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 165 "Providers are installed by name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide165

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.Authentication
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.basic

fun Application.module() {
  install(Authentication) {
    basic("auth") {
      realm = "Access to secrets"
      validate { credentials ->
        if (credentials.password == "supersecret") {
          UserIdPrincipal(credentials.name)
        } else {
          null
        }
      }
    }
  }
  routes()
}
