// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 167 "A scheme is a value, not a name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide167

import presentation.support.*
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.basic

val basicAuth = basic<UserIdPrincipal>("auth") {
  realm = "Access to secrets"
  validate { credentials ->
    if (credentials.password == "supersecret") {
      UserIdPrincipal(credentials.name)
    } else {
      null
    }
  }
}
