// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 169 "`authenticate` scopes the protected routes".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide169

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticate
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticate("auth") {
      get<Greeting.Hello> { req ->
        call.respondText("Hello, ${req.parent.name}")
      }
    }
  }
}
