// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 170 "`authenticate` scopes the protected routes".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide170

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticate
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticate("auth") {
      get<Greeting.Hello> { req ->
        val user = call.principal<UserIdPrincipal>()
        call.respondText("Hello, ${user?.name}")
      }
    }
  }
}
