// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 172 "The principal is typed and never `null`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide172

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(basicAuth) {
      get<Greeting.Hello> { req ->
        val user: UserIdPrincipal = call.principal
        call.respondText("Hello, ${user.name}")
      }
    }
  }
}
