// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 175 "Several schemes share a principal type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide175

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWithAnyOf
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWithAnyOf<UserIdPrincipal>(basicAuth, formAuth) {
      get<Greeting.Hello> { req ->
        call.respondText("Hello, ${call.principal.name}")
      }
    }
  }
}
