// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 175 "The login route writes the session".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide175

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import io.ktor.server.sessions.SessionStorageMemory
import io.ktor.server.sessions.Sessions
import io.ktor.server.sessions.cookie
import io.ktor.server.sessions.sessions
import io.ktor.server.sessions.set
import kotlinx.serialization.Serializable

@Serializable
data class UserInfo(val name: String, val timezone: String)

fun Application.module() {
  install(Sessions) {
    cookie<UserInfo>("user", SessionStorageMemory())
  }
  routing {
    post("/login") {
      if (loggedIn) call.sessions.set(UserInfo(name, tz))
    }
  }
}
