// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 176 "`StatusPages` rewrites the response".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide176

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.statuspages.StatusPages
import io.ktor.server.plugins.statuspages.statusFile

fun Application.module() {
  install(StatusPages) {
    statusFile(
      HttpStatusCode.Unauthorized,
      HttpStatusCode.NotFound,
      filePattern = "static/error/#.html",
    )
  }
  routes()
}
