// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 179 "The session is the principal".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide179

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.Authentication
import io.ktor.server.auth.session
import io.ktor.server.response.respondRedirect
import io.ktor.server.sessions.SessionStorageMemory
import io.ktor.server.sessions.Sessions
import io.ktor.server.sessions.cookie
import kotlinx.serialization.Serializable

@Serializable
data class UserInfo(val name: String, val timezone: String)

fun Application.module() {
  install(Sessions) {
    cookie<UserInfo>("user", SessionStorageMemory())
  }
  install(Authentication) {
    session<UserInfo>("auth-session") {
      validate { info -> if (info.name in users) info else null }
      challenge { call.respondRedirect("/login") }
    }
  }
  routes()
}
