// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 179 "The message is not for the client".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide179

import presentation.support.*
import io.ktor.http.HttpStatusCode
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.html.respondHtml
import io.ktor.server.plugins.statuspages.StatusPages
import kotlinx.html.body
import kotlinx.html.h1
import kotlinx.html.p

fun Application.module(logger: Logger) {
  install(StatusPages) {
    exception<Throwable> { call, cause ->
      logger.log("db: ${cause.message}")
      call.respondHtml(HttpStatusCode.InternalServerError) {
        body {
          h1 { +"This is embarrassing" }
        }
      }
    }
  }
  routes()
}
