// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 180 "The handler asks for the session type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide180

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticate
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticate("auth-session") {
      get<Greeting.Hello> { req ->
        val user = call.principal<UserInfo>()
        call.respondText("Hello, ${user?.name} in ${user?.timezone}")
      }
    }
  }
}
