// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 183 "The handler gets both".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide183

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.principal
import io.ktor.server.auth.session
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(sessionAuth) {
      get<Greeting.Hello> { req ->
        val user: UserIdPrincipal = call.principal
        call.respondText("Hello, ${user.name} in ${call.session.timezone}")
      }
    }
  }
}
