// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 185 "A test runs server and client in one process".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide185

import presentation.support.*
import io.kotest.matchers.shouldBe
import io.ktor.client.request.get
import io.ktor.http.HttpStatusCode
import io.ktor.server.testing.testApplication
import org.junit.jupiter.api.Test

class GreetingTest {
  @Test
  fun bye() = testApplication {
    application { module() }
    val response = client.get("/greet/alex/bye")
    response.status shouldBe HttpStatusCode.OK
  }
}
