// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 186 "Optional means `principalOrNull`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide186

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWithOptional
import io.ktor.server.auth.principalOrNull
import io.ktor.server.routing.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.routes() {
  routing {
    authenticateWithOptional(basicAuth) {
      get("/greet/{name}/hello") {
        val name: String by call.pathParameters
        val user: UserIdPrincipal? = call.principalOrNull
        call.respondText("Hello, ${user?.name ?: name}")
      }
    }
  }
}
