// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 188 "A scheme is a value, not a name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide188

import presentation.support.*
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.basic
import io.ktor.server.auth.form

val basicAuth = basic<UserIdPrincipal>("auth") {
  realm = "Access to secrets"
  validate { checkCredentials(it) }
}

val formAuth = form<UserIdPrincipal>("auth-form") {
  usernameField = "username"
  passwordField = "password"
  validate { checkCredentials(it) }
}
