// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 189 "The client forgets cookies unless told".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide189

import presentation.support.*
import io.ktor.client.HttpClient
import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
import io.ktor.client.plugins.cookies.HttpCookies
import io.ktor.serialization.kotlinx.json.json
import io.ktor.server.testing.testApplication

fun appTest(test: suspend (HttpClient) -> Unit) = testApplication {
  application { module() }
  val client = createClient {
    install(ContentNegotiation) { json() }
    install(HttpCookies)
    expectSuccess = true
  }
  test(client)
}
