// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 190 "The handler reads the claim back".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide190

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticate
import io.ktor.server.auth.jwt.JWTPrincipal
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticate("auth-jwt") {
      get<Greeting.Hello> { req ->
        val principal = call.principal<JWTPrincipal>()
        val user = principal?.payload?.getClaim("username")?.asString()
        call.respondText("Hello, $user")
      }
    }
  }
}
