// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 191 "The transport belongs to the scheme".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide191

import presentation.support.*
import io.ktor.server.auth.SessionTransportType
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.session
import io.ktor.server.response.respondRedirect
import io.ktor.server.sessions.SessionStorageMemory
import kotlinx.serialization.Serializable

@Serializable
data class UserInfo(val name: String, val timezone: String)

val sessionAuth = session<UserInfo, UserIdPrincipal>("auth-session") {
  transport = SessionTransportType.CookieId(SessionStorageMemory()) {
    cookie.maxAgeInSeconds = 3600
  }
  validate { info ->
    if (info.name in users) UserIdPrincipal(info.name) else null
  }
  onUnauthorized = { call.respondRedirect("/login") }
}
