// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 196 "Signing out clears the session".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide196

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.clearSession
import io.ktor.server.auth.principal
import io.ktor.server.auth.session
import io.ktor.server.routing.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(sessionAuth) {
      get("/greet/{name}/hello") {
        val user: UserIdPrincipal = call.principal
        call.respondText("Hello, ${user.name} in ${call.session.timezone}")
      }
      post("/logout") {
        sessionAuth.clearSession()
        call.respondText("Bye")
      }
    }
  }
}
