// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 196 "A missing role is `403`, not `401`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide196

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.principal
import io.ktor.server.auth.roles
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(roleAuth, roles = setOf(Role.Admin)) {
      get<Greeting.Hello> { req ->
        val roles: Set<Role> = call.principal.roles
        call.respondText("Hello, ${call.principal.name}: $roles")
      }
    }
  }
}
