// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 198 "The login signs the token".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide198

import presentation.support.*
import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import io.ktor.server.application.Application
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    post("/login") {
      if (loggedIn) {
        val token = JWT.create()
          .sign(Algorithm.HMAC256(secret))
      }
    }
  }
}
