// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 199 "Every application has a logger".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide199

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.log
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.module() {
  log.info("Greetings module loaded")
  routing {
    get("/greet/{name}/bye") {
      val name: String by call.pathParameters
      call.application.log.warn("{} is leaving", name)
      call.respondText("Bye, $name")
    }
  }
}
