// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 200 "`CallLogging` writes one line per request".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide200

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.calllogging.CallLogging
import io.ktor.server.request.path
import org.slf4j.event.Level

fun Application.module() {
  install(CallLogging) {
    level = Level.INFO
    filter { call -> !call.request.path().startsWith("/metrics") }
  }
  routes()
}
