// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 201 "The provider's session is a scheme".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide201

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(google.session) {
      get<Greeting.Hello> { req ->
        call.respondText("Hello, ${call.principal.userInfo.name}")
      }
    }
  }
}
