// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 202 "The login route writes the session".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide202

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.install
import io.ktor.server.auth.setSession
import io.ktor.server.routing.post
import io.ktor.server.routing.routing

fun Application.module() {
  install(sessionAuth)
  routing {
    post("/login") {
      if (loggedIn) sessionAuth.setSession(UserInfo(name, tz))
    }
  }
  routes()
}
