// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 202 "`mapPrincipal` makes it your user again".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide202

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.mapPrincipal
import io.ktor.server.auth.principal
import io.ktor.server.resources.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

val googleAuth = google.session.mapPrincipal { token ->
  UserIdPrincipal(token.userInfo.name ?: token.userInfo.subject)
}

fun Application.routes() {
  routing {
    authenticateWith(googleAuth) {
      get<Greeting.Hello> { req ->
        call.respondText("Hello, ${call.principal.name}")
      }
    }
  }
}
