// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 207 "Too many logins is a `429`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide207

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.ratelimit.RateLimit
import io.ktor.server.plugins.ratelimit.RateLimitName
import io.ktor.server.plugins.ratelimit.rateLimit
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import kotlin.time.Duration.Companion.minutes

fun Application.module() {
  install(RateLimit) {
    register(RateLimitName("login")) {
      rateLimiter(limit = 5, refillPeriod = 1.minutes)
    }
  }
  routing {
    rateLimit(RateLimitName("login")) {
      post("/login") { issueToken() }
    }
  }
}
