// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 208 "The login signs the token".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide208

import presentation.support.*
import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import io.ktor.server.application.Application
import io.ktor.server.response.respond
import io.ktor.server.routing.post
import io.ktor.server.routing.routing
import java.util.Date

fun Application.routes() {
  routing {
    post("/login") {
      if (loggedIn) {
        val token = JWT.create()
          .withClaim("username", name)
          .withExpiresAt(Date(System.currentTimeMillis() + 60_000))
          .sign(Algorithm.HMAC256(secret))
        call.respond(mapOf("token" to token))
      }
    }
  }
}
