// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 208 "One issuer URL configures the provider".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide208

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.oidc.Oidc

suspend fun Application.module() {
  val oidc = install(Oidc)
  val google = oidc.identityProvider("google") {
    issuer = "https://accounts.google.com"
  }
}
