// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 210 "A browser signs in at the provider".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide210

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.oidc.Oidc
import io.ktor.server.response.respondRedirect

suspend fun Application.module() {
  val oidc = install(Oidc)
  val google = oidc.identityProvider("google") {
    issuer = "https://accounts.google.com"
    oauth {
      clientId = System.getenv("GOOGLE_CLIENT_ID")
      clientSecret = System.getenv("GOOGLE_CLIENT_SECRET")
      onAuthenticated { idToken ->
        call.respondRedirect("/greet/${idToken.userInfo.name}/hello/9")
      }
    }
  }
}
