// Generated by slidev-theme-kotlin from lessons/lesson-8.md, slide 211 "Verify the signature, then the claims".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson8.slide211

import presentation.support.*
import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.jwt.jwt

val jwtAuth = jwt<UserIdPrincipal>("auth-jwt") {
  realm = "Access to secrets"
  verifier(JWT.require(Algorithm.HMAC256(secret)).build())
}
