// Generated by slidev-theme-kotlin from lessons/lesson-10.md, slide 257 "The server stops in two phases".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson10.slide257

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.ApplicationStarted
import io.ktor.server.application.ApplicationStopping
import io.ktor.server.application.log

fun Application.module() {
  monitor.subscribe(ApplicationStarted) { log.info("Ready") }
  monitor.subscribe(ApplicationStopping) { log.info("Draining requests") }
  routes()
}
