// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 198 "`EngineMain` reads a file instead".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide198

import presentation.support.*

fun main(args: Array<String>): Unit =
  io.ktor.server.netty.EngineMain.main(args)
