// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 208 "A scheme is a value, not a name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide208

import presentation.support.*
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.basic

val basicAuth = basic<UserIdPrincipal>("auth") {
  realm = "Access to secrets"
}
