// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 212 "Validation returns a principal or `null`".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide212

import presentation.support.*
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.UserPasswordCredential
import io.ktor.server.auth.ldap.ldapAuthenticate

fun checkCredentials(credentials: UserPasswordCredential): UserIdPrincipal? =
  ldapAuthenticate(credentials, "ldap://localhost:389", "cn=%s,dc=example")
