// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 213 "`authenticateWith` takes the scheme, not its name".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide213

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticateWith
import io.ktor.server.routing.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing
import io.ktor.server.util.getValue

fun Application.routes() {
  routing {
    authenticateWith(basicAuth) {
      get("/greet/{name}/hello") {
        val name: String by call.pathParameters
        call.respondText("Hello, $name")
      }
    }
  }
}
