// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 218 "`embeddedServer` can carry a configuration".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide218

import presentation.support.*
import io.ktor.server.config.MapApplicationConfig
import io.ktor.server.engine.applicationEnvironment
import io.ktor.server.engine.connector
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main() {
  embeddedServer(
    Netty,
    environment = applicationEnvironment {
      config = MapApplicationConfig("app.name" to "Awesome Ktor app")
    },
    configure = { connector { port = 8080 } },
  ) { module() }.start(wait = true)
}
