// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 220 "A session scheme names what is stored".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide220

import presentation.support.*
import io.ktor.server.auth.session
import kotlinx.serialization.Serializable

@Serializable
data class UserInfo(val name: String, val timezone: String)

val sessionAuth = session<UserInfo, UserInfo>("auth-session") {
  validate { it }
}
