// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 222 "Stored and used are two types".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide222

import presentation.support.*
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.session
import io.ktor.server.response.respondRedirect
import kotlinx.serialization.Serializable

@Serializable
data class UserInfo(val name: String, val timezone: String)

val sessionAuth = session<UserInfo, UserIdPrincipal>("auth-session") {
  validate { info ->
    if (info.name in users) UserIdPrincipal(info.name) else null
  }
  onUnauthorized = { call.respondRedirect("/login") }
}
