// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 227 "The module reads its own keys".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide227

import presentation.support.*
import io.ktor.server.application.Application

fun Application.module() {
  val token = environment.config.property("github.token").getString()
  routes()
}
