// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 228 "`embeddedServer` configures in code".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide228

import presentation.support.*
import io.ktor.server.engine.connector
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main() {
  embeddedServer(
    Netty,
    configure = {
      connector {
        host = "0.0.0.0"
        port = 8080
      }
    },
  ) { module() }.start(wait = true)
}
