// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 228 "`embeddedServer` configures in code".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide228

import presentation.support.*
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main() {
  embeddedServer(Netty, port = 8080, host = "0.0.0.0") { module() }
    .start(wait = true)
}
