// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 232 "Hoplite maps files to your own type".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide232

import presentation.support.*
import com.sksamuel.hoplite.ConfigLoaderBuilder
import com.sksamuel.hoplite.addResourceSource

data class Config(val name: String, val version: String)

val config: Config = ConfigLoaderBuilder.default()
  .addResourceSource("/defaults.conf")
  .build()
  .loadConfigOrThrow<Config>()
