// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 235 "Verify the signature, then the claims".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide235

import presentation.support.*
import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm
import io.ktor.http.HttpStatusCode
import io.ktor.server.auth.UserIdPrincipal
import io.ktor.server.auth.jwt.jwt
import io.ktor.server.response.respond

val jwtAuth = jwt<UserIdPrincipal>("auth-jwt") {
  realm = "Access to secrets"
  verifier(JWT.require(Algorithm.HMAC256(secret)).build())
  validate { credential ->
    val user = credential.payload.getClaim("username").asString()
    if (user.isNullOrEmpty()) null else UserIdPrincipal(user)
  }
  onUnauthorized = { cause ->
    call.respond(HttpStatusCode.Unauthorized, "Token invalid or expired")
  }
}
