// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 236 "The handler never parses the token".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide236

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.principal
import io.ktor.server.routing.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

fun Application.routes() {
  routing {
    authenticateWith(jwtAuth) {
      get("/greet/{name}/hello") {
        call.respondText("Hello, ${call.principal.name}")
      }
    }
  }
}
