// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 237 "Roles are resolved after authentication".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide237

import presentation.support.*
import io.ktor.server.auth.AuthenticationRole
import io.ktor.server.auth.withRoles

enum class Role : AuthenticationRole { User, Admin }

val roleAuth = jwtAuth.withRoles { user ->
  if (user.name == "Alex") setOf(Role.User, Role.Admin) else setOf(Role.User)
}
