// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 238 "The module reads its own keys".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide238

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.plugins.di.annotations.Property

fun Application.module(@Property("github.token") token: String) {
  routes()
}
