// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 238 "A proxy terminates TLS".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide238

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.plugins.forwardedheaders.XForwardedHeaders
import io.ktor.server.plugins.origin
import io.ktor.server.response.respondText
import io.ktor.server.routing.get
import io.ktor.server.routing.routing

fun Application.module() {
  install(XForwardedHeaders)
  routing {
    get("/whoami") {
      val origin = call.request.origin
      call.respondText("${origin.remoteHost} over ${origin.scheme}")
    }
  }
}
