// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 241 "An API validates the tokens it is handed".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide241

import presentation.support.*
import io.ktor.server.application.Application
import io.ktor.server.application.install
import io.ktor.server.auth.authenticateWith
import io.ktor.server.auth.oidc.Oidc
import io.ktor.server.auth.principal
import io.ktor.server.routing.get
import io.ktor.server.response.respondText
import io.ktor.server.routing.routing

suspend fun Application.module() {
  val oidc = install(Oidc)
  val google = oidc.identityProvider("google") {
    issuer = "https://accounts.google.com"
    bearer { audience = setOf("greetings-api") }
  }
  routing {
    authenticateWith(google.jwtBearer) {
      get("/greet/{name}/hello") {
        call.respondText("Hello, ${call.principal.claims.subject}")
      }
    }
  }
}
