// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 241 "`embeddedServer` can carry a configuration".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide241

import presentation.support.*
import com.typesafe.config.ConfigFactory
import io.ktor.server.config.HoconApplicationConfig
import io.ktor.server.engine.applicationEnvironment
import io.ktor.server.engine.connector
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

fun main() {
  embeddedServer(
    Netty,
    environment = applicationEnvironment {
      config = HoconApplicationConfig(ConfigFactory.load())
    },
    configure = { connector { port = 8080 } },
  ) { module() }.start(wait = true)
}
