// Generated by slidev-theme-kotlin from lessons/lesson-9.md, slide 244 "Secrets never live in the source".
// Do not edit: change the slide and run `slidev-kotlin-snippets` again.

package presentation.snippets.lesson9.slide244

import presentation.support.*
import com.auth0.jwt.JWT
import com.auth0.jwt.algorithms.Algorithm

val secret = "supersecret"

val token: String = JWT.create().sign(Algorithm.HMAC256(secret))
